# train_file: 'RU_senti_2022/data1/train.json'
# val_file: 'RU_senti_2022/data1/dev.json'                
# test_file: 'RU_senti_2022/data1/test.json'
# train_file: 'ewu/train.json'
# val_file: 'ewu/dev.json'                
# test_file: 'ewu/test.json'
train_file: 'MVSA_Single/train.json'
val_file: 'MVSA_Single/test.json'                
test_file: 'MVSA_Single/dev.json'
# train_file: 'MVSA_Single/train_own/train.json'
# val_file: 'MVSA_Single/train_own/dev.json'                
# test_file: 'MVSA_Single/train_own/test.json'
# test_file: 'MVSA_Single/dev.json'
# train_file: 'MVSA_Single/train_own2/train.json'
# val_file: 'MVSA_Single/train_own2/dev.json'                
# test_file: 'MVSA_Single/train_own2/test.json'
# train_file: 'MVSA_mul2/train.json'
# val_file: 'MVSA_mul2/dev.json'                
# test_file: 'MVSA_mul2/test.json'
# train_file: 'MVSA_mul2/train.json'
# val_file: 'MVSA_mul2/dev.json'                
# test_file: 'MVSA_mul2/test.json'
# train_file: 'MVSA_mul/train_own/train.json'
# val_file: 'MVSA_mul/train_own/dev.json'                
# test_file: 'MVSA_mul/train_own/test.json'
# train_file: 'MVSA_mul/train_own2/train.json'
# val_file: 'MVSA_mul/train_own2/dev.json'                
# test_file: 'MVSA_mul/train_own2/test.json'
# train_file: 'RU_senti_2022/data1/train.json'
# val_file: 'RU_senti_2022/data1/dev.json'                
# test_file: 'RU_senti_2022/data1/test.json'

# train_file: 'MVSA_Single/0424_4_ub/train.json'
# val_file: 'MVSA_Single/0424_4_ub/dev.json'                
# test_file: 'MVSA_Single/0424_4_ub/test.json'

# train_file: 'MVSA_mul2/0424_3/train.json'
# val_file: 'MVSA_mul2/0424_3/dev.json'                
# test_file: 'MVSA_mul2/0424_3/test.json'
# train_file: 'MVSA_mul2/0428_2/train1.json'
# val_file: 'MVSA_mul2/0428_2/dev.json'                
# test_file: 'MVSA_mul2/0428_2/test.json'

# each train_file (json) contains a python list where each item is {'image': img_path, 'caption': text or list_of_text }               
bert_config: 'configs/config_bert.json'
fusion_bert_config: 'configs/config_bert_fusion.json'
# fusion_bert_config: 'configs/config_bert_fusion_m.json'

image_res: 256
vision_width: 768
embed_dim: 256
batch_size: 32
# 32
# batch_size: 16
distill: True
warm_up: False

temp: 0.07
alpha: 0.4
queue_size: 8192
momentum: 0.995

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02} #lr 1e-4 to 1e-5
schedular: {sched: cosine, lr: 2e-5', epochs: 30, min_lr: 2e-5, decay_rate: 1, warmup_lr: 2e-5, warmup_epochs: 20, cooldown_epochs: 0}







